name: dart_with_sqlite3
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.6.2

dependencies:
  args: ^2.5.0
  ffi: ^2.1.3
  sqlite3: ^2.7.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
